// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh4u8L_fCkb4Rx6TM6eDXEKiq68ziyLeE',
    appId: '1:225442548024:web:139a027af22f44a6f299cd',
    messagingSenderId: '225442548024',
    projectId: 'ai-resume-reach',
    authDomain: 'ai-resume-reach.firebaseapp.com',
    storageBucket: 'ai-resume-reach.appspot.com',
    measurementId: 'G-4NT5R1W5N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD95Ce4Y7PwTH8B_fMisr69aSDrs7-658',
    appId: '1:225442548024:android:b28c0be5261499e5f299cd',
    messagingSenderId: '225442548024',
    projectId: 'ai-resume-reach',
    storageBucket: 'ai-resume-reach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD4cMHOdzCPe_8Mxc0IA6fZTflFQzZNdw',
    appId: '1:225442548024:ios:9fdf242cb2ff1002f299cd',
    messagingSenderId: '225442548024',
    projectId: 'ai-resume-reach',
    storageBucket: 'ai-resume-reach.appspot.com',
    iosBundleId: 'com.example.aiResumeReach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD4cMHOdzCPe_8Mxc0IA6fZTflFQzZNdw',
    appId: '1:225442548024:ios:9fdf242cb2ff1002f299cd',
    messagingSenderId: '225442548024',
    projectId: 'ai-resume-reach',
    storageBucket: 'ai-resume-reach.appspot.com',
    iosBundleId: 'com.example.aiResumeReach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh4u8L_fCkb4Rx6TM6eDXEKiq68ziyLeE',
    appId: '1:225442548024:web:020db786f3699255f299cd',
    messagingSenderId: '225442548024',
    projectId: 'ai-resume-reach',
    authDomain: 'ai-resume-reach.firebaseapp.com',
    storageBucket: 'ai-resume-reach.appspot.com',
    measurementId: 'G-L3RNW5MWZ7',
  );
}
